# Generated by Django 6.0.3 on 2026-04-23 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoria_id_alter_componente_id_devolucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_nombre', models.CharField(max_length=150)),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('SALIDA', 'Salida (Pedido)'), ('ENTRADA', 'Entrada (Devolución)')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Ej: RES-001', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Estante A, Gaveta 3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='componente',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
