# Generated by Django 6.0.3 on 2026-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_historialmovimiento_componente_codigo_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='precio_compra_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo Promedio ponderado de adquisición', max_digits=10),
        ),
        migrations.AddField(
            model_name='componente',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio al que se vende al publico', max_digits=10),
        ),
    ]
